name: lint
on:
  push:
    branches:
      - main
  pull_request: {}

permissions: read-all

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@774c35bcccffb734694af9e921f12f57d882ef74
        with:
          version: v1.60.3
          args: --config=.golangci.yml --verbose --out-${NO_FUTURE}format colored-line-number
          skip-cache: true